# .github/workflows/chromatic.yml

name: 'Chromatic'

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        working-directory: client
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: 2ca951af1de1
          workingDir: client
